---
final_name: postgres
min_cli_version: 1.5.0.pre.1001
blobstore:
  provider: local
  options:
    blobstore_path: /tmp/postgres
#  provider: s3
#  options:
#    bucket_name: postgres-release-blobs
